#!/usr/bin/python3

'''
    Flow - TheFlow - Join The Flow!
    Copyright (C) 2018  williamflow

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
'''

import zmq
from Database import Database
from Config import HOST, USER, PASSWD, DATABASE, CONNTABLE, ROUTERADDRESS

class Flow:
    def __init__(self, host, user, passwd, database, table, address):
        self.database = Database(host, user, passwd, database)
        self.table = table
        self.connection = zmq.Context().socket(zmq.ROUTER)
        self.connection.bind(address)
        while True:
            data = self.receive()
            self.route(data)
        
    def receive(self):
        packet = self.connection.recv_multipart()
        data = []
        for part in packet:
            try:
                data.append(part.decode("ascii"))
            except:
                data.append("")
        print("RECEIVED: ", str(data))
        return data
        
    def route(self, data):
        i = len(data)-1
        while i>0:
            for nodein in self.database.select(self.table, "nodein", nodeout=".".join(data[:i])):
                node = nodein.split(".")
                self.send(node+data[i:])
                i = 0
            i = i-1
    
    def send(self, data):
        packet = []
        for part in data:
            try:
                packet.append(str(part).encode("utf-8"))   
            except:
                packet.append("".encode("utf-8"))
        print("SENT ROUTER: ", str(data))
        self.connection.send_multipart(packet)

if __name__ == "__main__":
    flow = Flow(HOST, USER, PASSWD, DATABASE, CONNTABLE, ROUTERADDRESS)
