#!/usr/bin/python3

from zmqDealer import zmqDealer
from Database import Database
import traceback
import Flowctl
import ast
import uuid
from Config import *

SETTINGSMESSAGEOK = "I've sent you a link in private chat"
SETTINGSMESSAGENO = "Only admins can use this commands"
WEBSITE = "https://viadif.ga/telegram.html&webid="

class Telegramctl(zmqDealer):
    def __init__(self, identity, graph):
        zmqDealer.__init__(self, identity)
        messages = {}
        while True:
            data = self.receive()
            print("Telegramctl receive: ", data)
            try:
                updateid = data[-3]
                if not hasattr(this.messages, updateid):
                    this.messages[updateid] = {}
                tag = data[-2]
                value = data[-1]
                if not hasattr(this.messages[updateid], tag):
                    this.messages[updateid][tag] = value
                #TODO
                '''
                if data[-1] == "update":
                    update = ast.literal_eval(data[-2])
                    text = update["message"]["text"]
                    if text == "/settings" or text == "/settings@theflow_bot":
                        self.send(data[:-1]+["getadmins"])
                    else:
                        self.send(data[:-2]+[update["message"]["chat"]["id"], data[-2]])
                elif data[-2] == "admins":
                    update = asd.literal_eval(data[-3])
                    isAdmins=False
                    if update["message"]["from"]["id"] in data[-1].split(","):
                        database = Database(HOST, USER, PASSWD, DATABASE)
                        webid = False
                        for row in database.select("telegramchats", chatid, webid):
                            if row["chatid"] == update["message"]["chat"]["id"]:
                                webid = row["webid"]
                        if webid == False:
                            webid = uuid.uuid4()
                            database.insert("telegramchats", webid=webid, chatid=update["message"]["chat"]["id"])
                        self.send([str({"message":{"chat":{"id":update["message"]["from"]["id"]}}})]+["send", WEBSITE+webid])
                        self.send(data[:-2]+["send", SETTINGSMESSAGEOK])
                        '''
                    
            except:
                traceback.print_exc()

if __name__ == "__main__":
    Telegramctl("telegramctl", "parse")
